repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check . --fix
        language: system
        types: [python]
        pass_filenames: false
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy . --config-file=pyproject.toml
        language: system
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Optional: run tests locally before commit (uncomment to enable)
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
