name: CI

on:
  push:
    branches: [ "main", "feat/cli" ]
  pull_request:
    branches: [ "main", "feat/cli" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Cache Poetry and pip
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: python -m pip install --upgrade pip && pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-ansi

      - name: Run ruff (lint)
        run: poetry run ruff check .

      - name: Run black --check
        run: poetry run black --check .

      - name: Run mypy
        run: poetry run mypy .

      - name: Run tests
        run: poetry run pytest -q
